# Generated by Django 6.0.5 on 2026-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_partner_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_logos/'),
        ),
    ]
