# Generated by Django 6.0.5 on 2026-05-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_partner_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partner_extra_banners/')),
                ('order', models.IntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_banners', to='store.partner')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
