# Generated by Django 6.0.5 on 2026-05-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_partnerbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text="Named URL (e.g. 'home', 'shop_grid') or path (e.g. '/shop/')", max_length=200)),
                ('url_type', models.CharField(choices=[('named_url', 'Named URL'), ('path', 'Path')], default='named_url', max_length=20)),
                ('match_startswith', models.BooleanField(default=False, help_text='Check if request path starts with this URL (for Dashboard sub-pages)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('login_required', models.BooleanField(default=False, help_text='Only show to logged-in users')),
                ('logout_required', models.BooleanField(default=False, help_text='Only show to logged-out users')),
            ],
            options={
                'verbose_name_plural': 'Nav Menu',
                'ordering': ['order'],
            },
        ),
    ]
