# Generated by Django 6.0.5 on 2026-05-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_navmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerNavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='URL or named URL (leave blank for parent items with sub-menus)', max_length=500)),
                ('url_type', models.CharField(choices=[('named_url', 'Named URL'), ('path', 'Path')], default='named_url', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('login_required', models.BooleanField(default=False)),
                ('logout_required', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.partnernavmenu')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_menu_items', to='store.partner')),
            ],
            options={
                'verbose_name_plural': 'Partner Nav Menus',
                'ordering': ['order'],
            },
        ),
    ]
