# Generated by Django 6.0.5 on 2026-05-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_sidebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_division',
            field=models.CharField(blank=True, max_length=100, verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_street',
            field=models.CharField(blank=True, max_length=300, verbose_name='Street / Village / House / Flat'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_upazila',
            field=models.CharField(blank=True, max_length=100, verbose_name='Upazila'),
        ),
    ]
