# Generated by Django 6.0.5 on 2026-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_partner_address_district_partner_address_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='voter_id',
            field=models.ImageField(blank=True, null=True, upload_to='voter_ids/', verbose_name='Voter ID Card'),
        ),
    ]
