# Generated by Django 6.0.5 on 2026-05-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelogo',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_name',
            field=models.CharField(default='Uddoktar Dokan', max_length=200),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_tagline',
            field=models.CharField(blank=True, default='উদ্যোক্তার বাজার', max_length=200),
        ),
    ]
