# Generated by Django 6.0.5 on 2026-05-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g. https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
    ]
