# Generated by Django 6.0.5 on 2026-05-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_unit_label',
            field=models.CharField(blank=True, help_text="Custom unit label (e.g. 'Sack', 'Bundle')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(choices=[('cm', 'Cm'), ('inch', 'Inch'), ('m', 'M')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_on_request',
            field=models.BooleanField(default=False, help_text="Show 'Price on Request' instead of fixed price"),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kg'), ('liter', 'Liter'), ('dozen', 'Dozen'), ('pack', 'Pack'), ('box', 'Box'), ('custom', 'Custom')], default='piece', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'Gram'), ('lb', 'Lb'), ('oz', 'Oz')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('color_code', models.CharField(help_text='Hex color code, e.g. #FF0000', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_variants/')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Extra price for this color variant', max_digits=10)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
