# Generated by Django 6.0.5 on 2026-05-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_custom_unit_label_product_dimension_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='store.partner', verbose_name='Dealer (Parent)'),
        ),
    ]
