# Generated by Django 6.0.5 on 2026-05-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_partner_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS for this page only'),
        ),
        migrations.AddField(
            model_name='page',
            name='custom_js',
            field=models.TextField(blank=True, help_text='Custom JavaScript for this page only'),
        ),
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for search engines', max_length=500),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Override title tag for SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='Show link in footer'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_header',
            field=models.BooleanField(default=False, help_text='Show link in header navigation'),
        ),
        migrations.AddField(
            model_name='page',
            name='template_name',
            field=models.CharField(choices=[('default', 'Default Layout'), ('full_width', 'Full Width Layout'), ('landing', 'Landing Page')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('hero_title', models.CharField(blank=True, max_length=300)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_background', models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='landing/hero/')),
                ('hero_overlay_color', models.CharField(blank=True, default='rgba(0,0,0,0.5)', help_text='CSS overlay color over hero background', max_length=20)),
                ('hero_cta_text', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('hero_cta_link', models.CharField(blank=True, max_length=500)),
                ('about_heading', models.CharField(blank=True, default='About Us', max_length=300)),
                ('about_content', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='landing/about/')),
                ('featured_products_heading', models.CharField(blank=True, default='Featured Products', max_length=300)),
                ('show_partners', models.BooleanField(default=True, help_text='Show partners/dealers section')),
                ('partners_heading', models.CharField(blank=True, default='Our Partners', max_length=300)),
                ('show_stats', models.BooleanField(default=False)),
                ('stat_1_label', models.CharField(blank=True, default='Products', max_length=100)),
                ('stat_1_value', models.IntegerField(default=0)),
                ('stat_2_label', models.CharField(blank=True, default='Partners', max_length=100)),
                ('stat_2_value', models.IntegerField(default=0)),
                ('stat_3_label', models.CharField(blank=True, default='Happy Customers', max_length=100)),
                ('stat_3_value', models.IntegerField(default=0)),
                ('stat_4_label', models.CharField(blank=True, default='Orders', max_length=100)),
                ('stat_4_value', models.IntegerField(default=0)),
                ('primary_color', models.CharField(blank=True, default='#e74847', help_text='Primary brand color (hex)', max_length=20)),
                ('secondary_color', models.CharField(blank=True, default='#333333', help_text='Secondary color (hex)', max_length=20)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for this landing page')),
                ('meta_title', models.CharField(blank=True, help_text='Override title tag for SEO', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines', max_length=500)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300)),
                ('bottom_cta_heading', models.CharField(blank=True, default='Ready to Get Started?', max_length=300)),
                ('bottom_cta_text', models.CharField(blank=True, default='Contact us today!', max_length=200)),
                ('bottom_cta_link', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('featured_products', models.ManyToManyField(blank=True, related_name='landing_pages', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
