# Generated by Django 6.0.5 on 2026-05-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_serverfee_order_admin_notes_order_applied_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=300)),
                ('product_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=50)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('seller_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_order', models.ForeignKey(blank=True, help_text='Auto-created Order when approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_order_source', to='store.order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='store.partner')),
            ],
            options={
                'verbose_name_plural': 'Custom Orders',
                'ordering': ['-created'],
            },
        ),
    ]
