# Generated by Django 6.0.5 on 2026-05-23 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_add_cost_price_and_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=500.0, help_text='Minimum withdrawal amount', max_digits=12)),
                ('max_withdrawal', models.DecimalField(decimal_places=2, default=0, help_text='0 = unlimited', max_digits=12)),
                ('withdrawal_fee_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('withdrawal_fee_value', models.DecimalField(decimal_places=2, default=1.0, help_text='Fee amount or percentage', max_digits=10)),
                ('auto_approve_withdrawals', models.BooleanField(default=False, help_text='Auto-approve withdrawals under min threshold')),
                ('max_pending_withdrawals', models.IntegerField(default=3, help_text='Max concurrent pending withdrawals per partner')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet Settings',
                'verbose_name_plural': 'Wallet Settings',
            },
        ),
        migrations.CreateModel(
            name='PartnerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_frozen', models.BooleanField(default=False, help_text='Prevents withdrawals when frozen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='store.partner')),
            ],
            options={
                'verbose_name': 'Partner Wallet',
                'verbose_name_plural': 'Partner Wallets',
            },
        ),
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], max_length=20)),
                ('account_number', models.CharField(max_length=100)),
                ('account_holder', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='store.partner')),
            ],
            options={
                'verbose_name': 'Payout Method',
                'verbose_name_plural': 'Payout Methods',
                'ordering': ['-is_default', '-created'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after fee deduction', max_digits=12)),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], max_length=20)),
                ('account_number', models.CharField(max_length=100)),
                ('account_holder', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, help_text='Required for Bank Transfer', max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True, help_text='Optional note from partner')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='store.partner')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('order_credit', 'Order Credit'), ('manual_credit', 'Manual Credit'), ('manual_debit', 'Manual Debit'), ('withdrawal', 'Withdrawal'), ('withdrawal_fee', 'Withdrawal Fee'), ('commission_refund', 'Commission Refund')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('reference_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.partnerwallet')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.withdrawalrequest')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created'],
            },
        ),
    ]
