# Generated by Django 6.0.5 on 2026-05-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_add_wallet_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current platform balance', max_digits=12)),
                ('total_commission_collected', models.DecimalField(decimal_places=2, default=0, help_text='Total admin commission earned', max_digits=12)),
                ('total_manual_credits_given', models.DecimalField(decimal_places=2, default=0, help_text='Total manual credits given to partners', max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Balance',
                'verbose_name_plural': 'Platform Balance',
            },
        ),
        migrations.AddField(
            model_name='partnerwallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bonus/referral money that cannot be withdrawn yet', max_digits=12),
        ),
        migrations.AddField(
            model_name='partnerwallet',
            name='total_admin_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative admin commission earned from this partner', max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('order_credit', 'Order Credit'), ('manual_credit', 'Manual Credit'), ('manual_debit', 'Manual Debit'), ('withdrawal', 'Withdrawal'), ('withdrawal_fee', 'Withdrawal Fee'), ('commission_refund', 'Commission Refund'), ('signup_bonus', 'Signup Bonus'), ('bonus_release', 'Bonus Released')], max_length=30),
        ),
    ]
