# Generated by Django 6.0.5 on 2026-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_platformbalance_partnerwallet_locked_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, choices=[('steadfast', 'Steadfast'), ('pathao', 'Pathao'), ('sundarban', 'Sundarban'), ('ecourier', 'eCourier'), ('redx', 'RedX'), ('sa_paribahan', 'SA Paribahan'), ('other', 'Other')], help_text='Selected courier service', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='Courier tracking number / product code', max_length=100),
        ),
    ]
