# Generated by Django 6.0.5 on 2026-05-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_productreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
