# Generated by Django 6.0.5 on 2026-05-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_cart_abandoned_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_union_agent',
            field=models.BooleanField(default=False),
        ),
    ]
