# Generated by Django 6.0.5 on 2026-05-26 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_partner_is_union_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.partner', verbose_name='Delivery from Partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_village',
            field=models.CharField(blank=True, max_length=200, verbose_name='Village'),
        ),
    ]
