# Generated by Django 6.0.5 on 2026-05-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_order_delivery_partner_partner_address_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='partner_delivery_enabled',
            field=models.BooleanField(default=True, verbose_name='Allow Partner/Dealer address selection in checkout'),
        ),
    ]
