# Generated by Django 6.0.5 on 2026-05-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_sitelogo_partner_delivery_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='address_village',
        ),
    ]
