# Generated by Django 6.0.5 on 2026-05-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_partner_address_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Method Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('account_type', models.CharField(blank=True, default='Personal', max_length=50, verbose_name='Account Type')),
                ('instructions', models.TextField(blank=True, help_text='Additional payment instructions shown to customer')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lowest first)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual Payment Method',
                'verbose_name_plural': 'Manual Payment Methods',
                'ordering': ['order', 'name'],
            },
        ),
    ]
