# Generated by Django 6.0.5 on 2026-05-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_manualpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='show_products',
            field=models.BooleanField(default=True, help_text='Turn off to hide all your products from the public website', verbose_name='Show Products on Website'),
        ),
    ]
