# Generated by Django 6.0.5 on 2026-05-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_posorder_posorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique product code for inventory tracking', max_length=100, verbose_name='SKU (Stock Keeping Unit)'),
        ),
    ]
