# Generated by Django 6.0.5 on 2026-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_category_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='show_all_products_section',
            field=models.BooleanField(default=True, verbose_name='Show "All Over Available Product" section on store page'),
        ),
        migrations.AddField(
            model_name='partner',
            name='show_random_products_section',
            field=models.BooleanField(default=True, verbose_name='Show "Random product list" section on store page'),
        ),
    ]
