# Generated by Django 6.0.5 on 2026-05-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_partner_show_all_products_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='show_slider',
            field=models.BooleanField(default=True, verbose_name='Show slider on store page'),
        ),
        migrations.CreateModel(
            name='PartnerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='partner_sliders/')),
                ('link_url', models.CharField(blank=True, help_text='Optional URL the slider links to', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='store.partner')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
