# Generated by Django 6.0.5 on 2026-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_partner_show_slider_partnerslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerslider',
            name='button_text',
            field=models.CharField(blank=True, default='Click for Partner', help_text='Text shown on the slide button', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerslider',
            name='max_height',
            field=models.PositiveIntegerField(default=400, help_text='Max slide height in pixels (max 500)'),
        ),
    ]
