# Generated by Django 6.0.5 on 2026-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_support_ticket_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trashed',
            field=models.BooleanField(default=False, help_text='Soft-deleted; moved to trash'),
        ),
        migrations.AddField(
            model_name='product',
            name='trashed_at',
            field=models.DateTimeField(blank=True, help_text='When the product was trashed', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_status', 'Order Status Changed'), ('payment_received', 'Payment Received'), ('wallet_credit', 'Wallet Credited'), ('withdrawal_status', 'Withdrawal Status'), ('new_review', 'New Review'), ('new_seller', 'New Seller Added'), ('admin_message', 'Admin Message'), ('ticket_update', 'Ticket Update')], max_length=30),
        ),
    ]
