# Generated by Django 6.0.5 on 2026-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_product_trash_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='shop_style',
            field=models.CharField(blank=True, choices=[('general', 'General Shop'), ('shoe', 'Shoe Shop'), ('medicine', 'Medicine Shop')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='medicine_brand_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='medicine_dosage_form',
            field=models.CharField(blank=True, help_text='e.g. "Tablet", "Syrup", "Capsule"', max_length=100, verbose_name='Dosage Form'),
        ),
        migrations.AddField(
            model_name='product',
            name='medicine_generic_name',
            field=models.CharField(blank=True, help_text='Active ingredient / generic name for searching', max_length=300, verbose_name='Generic Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='medicine_strength',
            field=models.CharField(blank=True, help_text='e.g. "500 mg"', max_length=100, verbose_name='Strength'),
        ),
    ]
