# Generated by Django 6.0.5 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_partner_shop_style_product_medicine_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='has_medicine_access',
            field=models.BooleanField(default=False, help_text='Grant access to the global medicine product catalog for POS', verbose_name='Medicine Catalog Access'),
        ),
    ]
