# Generated by Django 6.0.5 on 2026-05-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_partner_has_medicine_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRechargeInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "bKash Payment", "Bank Transfer"', max_length=200)),
                ('instruction_text', models.TextField(help_text='Full payment instructions shown to partners')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet Recharge Instruction',
                'verbose_name_plural': 'Wallet Recharge Instructions',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='medicine_pos_enabled',
            field=models.BooleanField(default=False, help_text='Master switch — enables Medicine POS with subscription tracking', verbose_name='Medicine POS Enabled'),
        ),
        migrations.CreateModel(
            name='MedicinePosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='paid', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_pos_orders', to='store.partner')),
            ],
            options={
                'verbose_name': 'Medicine POS Order',
                'verbose_name_plural': 'Medicine POS Orders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MedicineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Brand Name')),
                ('generic_name', models.CharField(blank=True, help_text='Active ingredient / generic name', max_length=300, verbose_name='Generic Name')),
                ('strength', models.CharField(blank=True, help_text='e.g. "500 mg"', max_length=100, verbose_name='Strength')),
                ('dosage_form', models.CharField(blank=True, help_text='e.g. "Tablet", "Syrup"', max_length=100, verbose_name='Dosage Form')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_products/')),
                ('description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved products appear in Medicine POS', verbose_name='Approved')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_requests', to='store.partner', verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Medicine Product',
                'verbose_name_plural': 'Medicine Products',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MedicinePosOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.medicineposorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.medicineproduct')),
            ],
            options={
                'verbose_name': 'Medicine POS Order Item',
                'verbose_name_plural': 'Medicine POS Order Items',
            },
        ),
        migrations.CreateModel(
            name='MedicineSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='inactive', max_length=20)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('next_payment_due', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_subscription', to='store.partner')),
            ],
            options={
                'verbose_name': 'Medicine Subscription',
                'verbose_name_plural': 'Medicine Subscriptions',
            },
        ),
    ]
