# Generated by Django 6.0.5 on 2026-05-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_medicine_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('order_credit', 'Order Credit'), ('manual_credit', 'Manual Credit'), ('manual_debit', 'Manual Debit'), ('withdrawal', 'Withdrawal'), ('withdrawal_fee', 'Withdrawal Fee'), ('commission_refund', 'Commission Refund'), ('signup_bonus', 'Signup Bonus'), ('bonus_release', 'Bonus Released'), ('subscription_payment', 'Subscription Payment')], max_length=30),
        ),
    ]
