# Generated by Django 6.0.5 on 2026-05-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_wallettransaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Monthly", "Quarterly", "Yearly"', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in BDT', max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Number of days the subscription lasts')),
                ('is_active', models.BooleanField(default=True, help_text='Show this package to partners')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
                ('description', models.TextField(blank=True, help_text='Short description/features of this package')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Package',
                'verbose_name_plural': 'Subscription Packages',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
