# Generated by Django 6.0.5 on 2026-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_subscriptionpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='blocked',
            field=models.BooleanField(default=False, help_text='When blocked, this partner cannot be deleted from admin (prevents cascade delete through related medicine models)', verbose_name='Block deletion'),
        ),
    ]
