# Generated by Django 6.0.5 on 2026-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_partner_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='UPC / EAN / QR code for POS scanning', max_length=100, verbose_name='Barcode'),
        ),
    ]
