# Generated by Django 6.0.5 on 2026-06-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Alert when stock falls below this number', verbose_name='Low Stock Threshold'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_status', 'Order Status Changed'), ('payment_received', 'Payment Received'), ('wallet_credit', 'Wallet Credited'), ('withdrawal_status', 'Withdrawal Status'), ('new_review', 'New Review'), ('new_seller', 'New Seller Added'), ('admin_message', 'Admin Message'), ('ticket_update', 'Ticket Update'), ('low_stock', 'Low Stock Alert')], max_length=30),
        ),
    ]
