# Generated by Django 6.0.5 on 2026-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorvariant',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock for this specific color (0 = use parent product stock)'),
        ),
        migrations.AddField(
            model_name='productsizevariant',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock for this specific size (0 = use parent product stock)'),
        ),
    ]
