# Generated by Django 6.0.5 on 2026-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_productcolorvariant_stock_productsizevariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='partner_favicon/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Custom URL when clicking logo (leave blank to link to homepage)', max_length=500),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site_favicon/'),
        ),
    ]
