# Generated by Django 6.0.5 on 2026-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_partner_favicon_partner_logo_url_sitelogo_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS for your store page'),
        ),
        migrations.AddField(
            model_name='partner',
            name='primary_color',
            field=models.CharField(blank=True, default='#e74847', help_text='Primary brand color for your store (hex)', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='secondary_color',
            field=models.CharField(blank=True, default='#333333', help_text='Secondary color for your store (hex)', max_length=20),
        ),
    ]
