# Generated by Django 6.0.5 on 2026-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_partner_custom_css_partner_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Custom Label'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('hot', 'Hot Item'), ('discounted', 'Discounted'), ('used', 'Used')], max_length=20, null=True),
        ),
    ]
