# Generated by Django 6.0.5 on 2026-06-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_product_custom_label_alter_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='theme',
            field=models.CharField(blank=True, choices=[('default', 'Default Red'), ('ocean_blue', 'Ocean Blue'), ('forest_green', 'Forest Green'), ('royal_purple', 'Royal Purple'), ('sunset_orange', 'Sunset Orange'), ('teal', 'Teal'), ('dark_mode', 'Dark Mode'), ('rose_pink', 'Rose Pink'), ('amber', 'Amber'), ('slate_gray', 'Slate Gray')], default='', help_text='Select a pre-built theme (overrides custom colors below)', max_length=30),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_primary_color',
            field=models.CharField(blank=True, default='#e74847', help_text='Site-wide primary color (hex)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_secondary_color',
            field=models.CharField(blank=True, default='#333333', help_text='Site-wide secondary color (hex)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_theme',
            field=models.CharField(blank=True, choices=[('default', 'Default Red'), ('ocean_blue', 'Ocean Blue'), ('forest_green', 'Forest Green'), ('royal_purple', 'Royal Purple'), ('sunset_orange', 'Sunset Orange'), ('teal', 'Teal'), ('dark_mode', 'Dark Mode'), ('rose_pink', 'Rose Pink'), ('amber', 'Amber'), ('slate_gray', 'Slate Gray')], default='', help_text='Site-wide theme (applies to homepage and all partner stores)', max_length=30),
        ),
    ]
